# ===----------------------------------------------------------------------=== #
# Copyright (c) 2026, Modular Inc. All rights reserved.
#
# Licensed under the Apache License v2.0 with LLVM Exceptions:
# https://llvm.org/LICENSE.txt
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ===----------------------------------------------------------------------=== #
"""Generate test_args.bzl content from Mojo solution files.

Reads the Mojo files passed as positional arguments, extracts flag patterns
using the same logic as run.sh, and writes a Starlark mapping to stdout.

Used as a genrule tool — output is consumed by write_source_files to keep
test_args.bzl in sync with the actual puzzle sources.
"""

import re
import sys
from pathlib import Path

# Mojo: argv()[1] == "--flag" or test_type == "--flag"
_MOJO_PATTERN = re.compile(
    r'argv\(\)\[1\]\s*==\s*"(--[^"]+)"|test_type\s*==\s*"(--[^"]+)"'
)
# Python: sys.argv[1] == "--flag" or any quoted "--flag" (covers argparse add_argument)
_PY_PATTERN = re.compile(r'"(--[a-z][a-z-]*)"')

_HEADER = """\
# ===----------------------------------------------------------------------=== #
# Copyright (c) 2026, Modular Inc. All rights reserved.
#
# Licensed under the Apache License v2.0 with LLVM Exceptions:
# https://llvm.org/LICENSE.txt
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ===----------------------------------------------------------------------=== #

# Auto-generated by //oss/mojo-gpu-puzzles/solutions:generate_test_args_bzl
# Run `./bazelw run //oss/mojo-gpu-puzzles/solutions:update_test_args` to regenerate.

\"\"\"Maps Mojo solution files to the command-line flags they accept.

Files absent from this mapping run as a single test with no arguments.
Files present in this mapping get one test target per flag.
\"\"\"

"""


def _extract_flags(path: Path) -> list[str]:
    text = path.read_text()
    pattern = _MOJO_PATTERN if path.suffix == ".mojo" else _PY_PATTERN
    flags: set[str] = set()
    for m in pattern.finditer(text):
        flag = next(g for g in m.groups() if g)
        if not flag.startswith("--demo"):
            flags.add(flag)
    return sorted(flags)


def main() -> None:
    source_files = sorted(
        Path(f) for f in sys.argv[1:] if f.endswith((".mojo", ".py"))
    )

    mapping: dict[str, list[str]] = {}
    for path in source_files:
        # Use the last two components (e.g. "p13/p13.mojo") as the key so
        # this works whether the paths come from genrule srcs or a local run.
        rel = "/".join(path.parts[-2:])
        flags = _extract_flags(path)
        if flags:
            mapping[rel] = flags

    lines = [_HEADER, "TEST_ARGS = {\n"]
    for src, flags in sorted(mapping.items()):
        flag_list = ", ".join(f'"{f}"' for f in flags)
        lines.append(f'    "{src}": [{flag_list}],\n')
    lines.append("}\n")
    sys.stdout.write("".join(lines))


if __name__ == "__main__":
    main()
